runtime: nodejs20
env: standard
instance_class: F1
env_variables:
  INSTANCE_HOST: "34.122.70.186"
  DB_USERNAME: "atlascopco_admin"
  DB_PASSWORD: "your-db-password"
  DATABASE: "AtlasCopco"
  DB_PORT: "3306"
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7